### ISSUE TITLE
Inconsistent results with CA/US numbers

### ISSUE THREAD

**Issue by calvinte** [andris9/PhoneNumber.js-for-the-Web#1]
```
> PhoneNumber.Parse('16475556445', 'US').region === 'US'
true

> PhoneNumber.Parse('16475556445', 'CA').region === 'CA'
true

> PhoneNumber.Parse('+16475556445', 'US').region === 'US'
true

> PhoneNumber.Parse('+16475556445', 'CA').region === 'CA'
false
```

Any idea why including or discluding the `+` causes this behaviour? 

Edit: don't want to list my personal phone number here... whoops.

**Comment by andris9** [comment]
See this answer: https://github.com/andris9/PhoneNumber.js-for-the-Web/issues/2#issuecomment-71471892
