### ISSUE TITLE
Results different based on provided 'Default Region'

### ISSUE THREAD

**Issue by calvinte** [andris9/PhoneNumber.js-for-the-Web#2]
I use the term "different" in the title for this issue because I'm unsure if this is intended behaviour, or actually a bug. You will see below that changing the `defaultRegion` to `AE` from `US` causes no formatted numbers or an international number to be returned (they're `null`). 

Any idea if this is the intended behaviour, or am I misunderstanding something?

```
> PhoneNumber.Parse('97125556065', 'US').internationalFormat === '+971 2 555 6065' ;
true
> PhoneNumber.Parse('97125556065', 'US').internationalNumber === '+97125556065' ;
true
> PhoneNumber.Parse('97125556065', 'US').nationalFormat === '02 555 6065' ;
true
> PhoneNumber.Parse('97125556065', 'US').nationalNumber === '25556065';
true

> PhoneNumber.Parse('97125556065', 'AE').internationalFormat === '+971 2 555 6065' ;
false
> PhoneNumber.Parse('97125556065', 'AE').internationalNumber === '+97125556065' ;
false
> PhoneNumber.Parse('97125556065', 'AE').nationalFormat === '02 555 6065' ;
false
> PhoneNumber.Parse('97125556065', 'AE').nationalNumber === '25556065';
true
```

**Comment by andris9** [comment]
You should check out [PhoneNumber.js](https://github.com/andreasgal/PhoneNumber.js), thats where the logic comes from. The original project is for firefox-os and this fork only does the minimal to get it running under regular web browsers but nothing more. If PhoneNumber.js changes something, then I'll port the changes here as well but I do not do anything with the logic myself.
